// Generated by scripts/generate-commands.mjs. Do not edit by hand; run
// `pnpm generate:commands` after adding, renaming, or removing a command.
import type { Command } from "commander";
import envCommand from './env.command.js';
import initCommand from './init.command.js';

/** Factories for every command in `src/commands/`, in filename order. */
export const commandFactories: ReadonlyArray<() => Command> = [
    envCommand,
    initCommand,
];
