// Generated by scripts/generate-templates.mjs from templates/node-ts/. Do not edit by hand; edit
// the template files and run `pnpm generate:templates`.

/** A file in the project template: its path relative to the project root, and its contents. */
export interface TemplateFile {
    /** Path relative to the new project's root, using `/` separators. */
    path: string;
    /** File contents. `{{name}}` is replaced with the project name. */
    contents: string;
}

/** Files `dev-setup bootstrap` creates, sorted by path. */
export const PROJECT_TEMPLATE: ReadonlyArray<TemplateFile> = [
    {
        path: ".env.example",
        contents: "# Copy to .env with `dev-setup init`, then fill in the values.\nPORT=3000\n",
    },
    {
        path: ".gitignore",
        contents: "node_modules/\ndist/\ncoverage/\n*.log\n\n# Local environment files (.env.example is the committed template)\n.env\n.env.*\n!.env.example\n",
    },
    {
        path: ".prettierignore",
        contents: "pnpm-lock.yaml\n",
    },
    {
        path: ".prettierrc.json",
        contents: "{\n  \"singleQuote\": true,\n  \"tabWidth\": 4,\n  \"printWidth\": 100,\n  \"overrides\": [\n    {\n      \"files\": [\"*.json\", \"*.yaml\", \"*.md\"],\n      \"options\": { \"tabWidth\": 2 }\n    }\n  ]\n}\n",
    },
    {
        path: "README.md",
        contents: "# {{name}}\n\nCreated with `dev-setup bootstrap`.\n\n## Getting started\n\n```bash\npnpm install\ndev-setup init    # check Node.js and pnpm, and create .env from .env.example\npnpm dev          # run src/index.ts\n```\n\n## Scripts\n\n| Script        | What it does                        |\n| ------------- | ----------------------------------- |\n| `pnpm dev`    | Runs `src/index.ts` with tsx        |\n| `pnpm build`  | Compiles `src/` to `dist/` with tsc |\n| `pnpm start`  | Runs the compiled `dist/index.js`   |\n| `pnpm test`   | Runs the Jest tests in `tests/`     |\n| `pnpm lint`   | Lints `src/` with ESLint            |\n| `pnpm format` | Formats the project with Prettier   |\n",
    },
    {
        path: "eslint.config.js",
        contents: "// @ts-check\nimport tseslint from 'typescript-eslint';\n\nexport default tseslint.config(tseslint.configs.recommended);\n",
    },
    {
        path: "jest.config.mjs",
        contents: "/** @type {import('jest').Config} */\nexport default {\n    roots: ['<rootDir>/tests'],\n    testEnvironment: 'node',\n    extensionsToTreatAsEsm: ['.ts'],\n    transform: {\n        '^.+\\\\.tsx?$': ['ts-jest', { useESM: true, tsconfig: '<rootDir>/tsconfig.json' }],\n    },\n    moduleNameMapper: {\n        '^(\\\\.{1,2}/.*)\\\\.js$': '$1',\n    },\n};\n",
    },
    {
        path: "package.json",
        contents: "{\n  \"name\": \"{{name}}\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"tsx src/index.ts\",\n    \"build\": \"tsc\",\n    \"start\": \"node dist/index.js\",\n    \"test\": \"node --experimental-vm-modules node_modules/jest/bin/jest.js --config jest.config.mjs\",\n    \"lint\": \"eslint src\",\n    \"format\": \"prettier --write .\"\n  },\n  \"devDependencies\": {\n    \"@types/jest\": \"^30.0.0\",\n    \"@types/node\": \"^26.6.3\",\n    \"eslint\": \"^10.11.0\",\n    \"jest\": \"^30.5.2\",\n    \"prettier\": \"^3.9.9\",\n    \"ts-jest\": \"^29.4.14\",\n    \"tsx\": \"^4.23.15\",\n    \"typescript\": \"^6.0.3\",\n    \"typescript-eslint\": \"^8.71.0\"\n  }\n}\n",
    },
    {
        path: "pnpm-workspace.yaml",
        contents: "# pnpm doesn't run dependency build scripts unless they're approved here.\nallowBuilds:\n  '@parcel/watcher': true\n  esbuild: true\n  unrs-resolver: true\n",
    },
    {
        path: "src/greet.ts",
        contents: "/**\n * Builds a greeting.\n *\n * @param name Who to greet.\n * @returns The greeting, e.g. `Hello, Ada!`.\n */\nexport const greet = (name: string): string => `Hello, ${name}!`;\n",
    },
    {
        path: "src/index.ts",
        contents: "import { greet } from './greet.js';\n\nconsole.log(greet('{{name}}'));\n",
    },
    {
        path: "tests/greet.test.ts",
        contents: "import { greet } from '../src/greet.js';\n\ndescribe('greet', () => {\n    it('greets by name', () => {\n        const result = greet('Ada');\n\n        expect(result).toBe('Hello, Ada!');\n    });\n});\n",
    },
    {
        path: "tsconfig.json",
        contents: "{\n  \"compilerOptions\": {\n    \"rootDir\": \"./src\",\n    \"outDir\": \"./dist\",\n    \"module\": \"nodenext\",\n    \"target\": \"esnext\",\n    \"lib\": [\"esnext\"],\n    \"types\": [\"node\", \"jest\"],\n    \"sourceMap\": true,\n    \"strict\": true,\n    \"noUncheckedIndexedAccess\": true,\n    \"noUnusedLocals\": true,\n    \"noUnusedParameters\": true,\n    \"noImplicitReturns\": true,\n    \"verbatimModuleSyntax\": true,\n    \"isolatedModules\": true,\n    \"skipLibCheck\": true\n  },\n  \"include\": [\"src/**/*.ts\"]\n}\n",
    },
];
