const { jest } = import.meta;

const TEMPLATE = '/repo/templates/node-ts';
const MODULE = '/repo/src/config/project-template.ts';

// In-memory filesystem: absolute path -> contents. Directories are implied by file paths.
let files: Record<string, string> = {};

const dirent = (name: string, isDirectory: boolean) => ({ name, isDirectory: () => isDirectory });

const writeFileSync = jest.fn((filePath: string, contents: string) => {
    files[filePath] = contents;
});

jest.unstable_mockModule('node:fs', () => ({
    existsSync: (filePath: string) => filePath in files,
    readdirSync: (dir: string) => {
        const names = new Map<string, boolean>();
        for (const filePath of Object.keys(files)) {
            if (!filePath.startsWith(`${dir}/`)) continue;
            const [name, ...rest] = filePath.slice(dir.length + 1).split('/');
            names.set(name as string, rest.length > 0);
        }
        return [...names].map(([name, isDirectory]) => dirent(name, isDirectory));
    },
    readFileSync: (filePath: string) => {
        const contents = files[filePath];
        if (contents === undefined) throw new Error(`ENOENT: ${filePath}`);
        return contents;
    },
    writeFileSync,
}));

const { generate, listFiles, readTemplate, renderTemplateModule, toOutputPath } =
    await import('../../scripts/generate-templates.mjs');

beforeEach(() => {
    files = {};
    writeFileSync.mockClear();
});

describe('toOutputPath', () => {
    it('renames _gitignore to .gitignore', () => {
        expect(toOutputPath('_gitignore')).toBe('.gitignore');
    });

    it('renames _gitignore in subdirectories', () => {
        expect(toOutputPath('packages/_gitignore')).toBe('packages/.gitignore');
    });

    it('leaves other paths unchanged', () => {
        expect(toOutputPath('src/my_gitignore.ts')).toBe('src/my_gitignore.ts');
    });
});

describe('listFiles', () => {
    it('lists files recursively with / separators', () => {
        files = {
            [`${TEMPLATE}/package.json`]: '{}',
            [`${TEMPLATE}/src/index.ts`]: '',
            [`${TEMPLATE}/src/lib/util.ts`]: '',
        };

        expect(listFiles(TEMPLATE).sort()).toEqual(['package.json', 'src/index.ts', 'src/lib/util.ts']);
    });
});

describe('readTemplate', () => {
    it('returns output paths and contents sorted by path', () => {
        files = {
            [`${TEMPLATE}/src/index.ts`]: 'code\n',
            [`${TEMPLATE}/_gitignore`]: 'dist/\n',
            [`${TEMPLATE}/README.md`]: '# {{name}}\n',
        };

        expect(readTemplate(TEMPLATE)).toEqual([
            { path: '.gitignore', contents: 'dist/\n' },
            { path: 'README.md', contents: '# {{name}}\n' },
            { path: 'src/index.ts', contents: 'code\n' },
        ]);
    });

    it('normalizes CRLF line endings to LF', () => {
        files = { [`${TEMPLATE}/README.md`]: '# a\r\nb\r\n' };

        expect(readTemplate(TEMPLATE)[0]?.contents).toBe('# a\nb\n');
    });

    it('throws when the template has no files', () => {
        expect(() => readTemplate(TEMPLATE)).toThrow(`${TEMPLATE} has no template files.`);
    });

    it('throws when two files map to the same output path', () => {
        files = { [`${TEMPLATE}/_gitignore`]: 'a', [`${TEMPLATE}/.gitignore`]: 'b' };

        expect(() => readTemplate(TEMPLATE)).toThrow(`${TEMPLATE} has more than one file for: .gitignore`);
    });
});

describe('renderTemplateModule', () => {
    it('renders each file as an escaped string literal', () => {
        const source = renderTemplateModule([{ path: 'a.json', contents: '{\n  "x": "`${y}`"\n}\n' }]);

        expect(source).toContain('        path: "a.json",\n');
        expect(source).toContain('        contents: "{\\n  \\"x\\": \\"`${y}`\\"\\n}\\n",\n');
        expect(source).toContain('export const PROJECT_TEMPLATE: ReadonlyArray<TemplateFile> = [\n');
    });

    it('marks the module as generated', () => {
        expect(renderTemplateModule([])).toMatch(/^\/\/ Generated by scripts\/generate-templates\.mjs/);
    });
});

describe('generate', () => {
    beforeEach(() => {
        files = { [`${TEMPLATE}/README.md`]: '# {{name}}\n' };
    });

    it('writes the module when it is missing', () => {
        expect(generate(TEMPLATE, MODULE)).toBe(true);

        expect(files[MODULE]).toBe(renderTemplateModule(readTemplate(TEMPLATE)));
    });

    it('does not rewrite a module that is up to date', () => {
        generate(TEMPLATE, MODULE);
        writeFileSync.mockClear();

        generate(TEMPLATE, MODULE);

        expect(writeFileSync).not.toHaveBeenCalled();
    });

    it('in check mode, returns false for a stale module without writing', () => {
        files[MODULE] = 'stale';

        expect(generate(TEMPLATE, MODULE, { check: true })).toBe(false);
        expect(writeFileSync).not.toHaveBeenCalled();
    });

    it('in check mode, returns false for a missing module', () => {
        expect(generate(TEMPLATE, MODULE, { check: true })).toBe(false);
    });

    it('in check mode, returns true for a current module', () => {
        generate(TEMPLATE, MODULE);

        expect(generate(TEMPLATE, MODULE, { check: true })).toBe(true);
    });
});
